color: null
fieldLayouts:
  ec0fbadd-bb15-4460-be73-dfe95e3d7b0e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 85601f71-fde7-42e0-9192-8b2979fdf289
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6e5feee-9d1f-4d45-9e41-ae8ac422dedb # genre
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71ebecab-fcb4-44f6-97a3-fcf8e6c82837
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5d2d0ac8-fa57-4e37-8b48-f143a98e122f
        userCondition: null
handle: genre
hasTitleField: true
icon: ''
name: genre
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
