color: null
fieldLayouts:
  5fe0fd26-bf4c-4263-8c99-00fb8df20492:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e7be83aa-c321-4330-912e-b69b54c7ff4c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3fea6f9-05e1-4432-8415-daed09945d73 # heroImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f7992fb-c790-4f85-a9ab-1e443fa6162e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a607c76c-8146-4075-b623-6525e20d60ad # align-switch
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09eb2027-90d6-49f6-ac1e-023e4120233f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5951ea82-d50f-4217-a695-e63b768c6d68
        userCondition: null
handle: heroImageTextBlock
hasTitleField: true
icon: ''
name: hero-image-text-block
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
