color: null
fieldLayouts:
  00106fe6-37c5-4815-83fb-34d68fe1ed73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6d121f7-a52b-4e71-9dac-cb496986f904
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3fea6f9-05e1-4432-8415-daed09945d73 # heroImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b04d6dd-78f3-4403-80a1-923030724029
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11932eb6-3d93-40ae-b27a-c4f14e09d251
        userCondition: null
handle: heroImageText
hasTitleField: true
icon: ''
name: hero-image-text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
