color: null
fieldLayouts:
  4e58b3cc-1c2e-4d60-b265-30a1d500ae95:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c70c7a71-7546-41b5-a4df-a52138e82712
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 28ab9931-1bb9-4848-a919-761dce603991 # manga-title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 152f7110-ecc4-4d23-86be-d71fbd7d1b51
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dfc0c543-f07c-4d11-ada3-df064298944a
        userCondition: null
handle: mangatitle
hasTitleField: true
icon: ''
name: mangatitle
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
