color: null
fieldLayouts:
  af8df72f-056a-44d5-b33a-b8ccd0f5970e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aae98753-efba-44ea-8288-db532b5c9c9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e545cf6d-6d1d-48f6-a20f-e397b393c58c
        userCondition: null
handle: productName
hasTitleField: true
icon: ''
name: product-name
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
