altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ba8056d8-1319-4d97-97ae-4c10d1f88a24:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f6c37f1f-6076-41b7-8416-a22a46cd9589
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0e182840-947d-4a54-b43c-f77c11dd6007
        userCondition: null
fs: files
handle: Files
name: Bestanden
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
