columnSuffix: null
handle: email
instructions: null
name: email
searchable: false
settings:
  placeholder: mangazine@gmail.com
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
