columnSuffix: null
handle: mangaSubtitle
instructions: 'Banner of the homepage'
name: manga-subtitle
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Dit is een intro'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
