defaultPlacement: end
enableVersioning: true
entryTypes:
  - 16bb7c47-6f25-44be-abd6-756dca384629 # default-two
handle: ages
maxAuthors: 1
name: Ages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c1520826-377f-476b-bf92-e4c997cf7ab2: # werkpakket-3
    enabledByDefault: true
    hasUrls: true
    template: ages/_entry
    uriFormat: 'ages/{slug}'
structure:
  maxLevels: null
  uid: 9f1ae735-16e5-4a06-9d3e-6deb22738e92
type: structure
