defaultPlacement: end
enableVersioning: true
entryTypes:
  - f49ced23-d13c-4ca8-ab56-ced762b3212b # default
handle: genres
maxAuthors: 1
name: Genres
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c1520826-377f-476b-bf92-e4c997cf7ab2: # werkpakket-3
    enabledByDefault: true
    hasUrls: true
    template: genres/_entry
    uriFormat: 'genres/{slug}'
structure:
  maxLevels: null
  uid: f2a16d33-633a-4ee3-9eb0-c074510fb159
type: structure
