defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5645c1b0-031f-4e21-a20c-fe082d0ef299 # header
handle: header
maxAuthors: 1
name: header
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c1520826-377f-476b-bf92-e4c997cf7ab2: # werkpakket-3
    enabledByDefault: true
    hasUrls: true
    template: _snippets/_header.twig
    uriFormat: 'header/{slug}'
type: channel
