defaultPlacement: end
enableVersioning: true
entryTypes:
  - b4f088cb-8d36-44ae-aa7f-c4c13e948a6e # homepage
handle: home
maxAuthors: 1
name: Startpagina
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c1520826-377f-476b-bf92-e4c997cf7ab2: # werkpakket-3
    enabledByDefault: true
    hasUrls: true
    template: _index.twig
    uriFormat: __home__
type: single
