defaultPlacement: end
enableVersioning: true
entryTypes:
  - f7db66ca-a7dc-44d2-bf83-7ef9537d4fa9 # productpage
handle: product
maxAuthors: 1
name: product
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c1520826-377f-476b-bf92-e4c997cf7ab2: # werkpakket-3
    enabledByDefault: true
    hasUrls: true
    template: product.twig
    uriFormat: 'product/{slug}'
type: channel
