defaultPlacement: end
enableVersioning: true
entryTypes:
  - c7cf490b-4912-4e58-967e-290203b2a838 # selfpage
handle: selfpage
maxAuthors: 1
name: Selfpage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c1520826-377f-476b-bf92-e4c997cf7ab2: # werkpakket-3
    enabledByDefault: true
    hasUrls: true
    template: selfpage.twig
    uriFormat: 'selfpage/{slug}'
type: channel
