defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3d29fff0-8e97-41a8-8519-09059373e628 # mangaProduct
handle: shop
maxAuthors: 1
name: Shop
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c1520826-377f-476b-bf92-e4c997cf7ab2: # werkpakket-3
    enabledByDefault: true
    hasUrls: true
    template: shop.twig
    uriFormat: 'shop/{slug}'
type: channel
